
package org.uddi.digitalindiatx.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.uddi.digitalindiatx.types.PayRecept;
import org.uddi.digitalindiatx.types.UddiPayment;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UddiGateWayManager", targetNamespace = "http://uddi.org/digitalindiatx/service",wsdlLocation="WEB-INF/UddiGateWayManager.wsdl")
@XmlSeeAlso({
    org.uddi.digitalindiatx.service.ObjectFactory.class,
    org.uddi.digitalindiatx.types.ObjectFactory.class
})
public interface UddiGateWayManager {


    /**
     * 
     * @param toAccount
     * @param balance
     * @param fromAccount
     * @return
     *     returns org.uddi.digitalindiatx.types.PayRecept
     */
    @WebMethod(action = "http://uddi.org/digitalindiatx/service/pay")
    @WebResult(name = "recept", targetNamespace = "http://uddi.org/digitalindiatx/types")
    @RequestWrapper(localName = "pay", targetNamespace = "http://uddi.org/digitalindiatx/service", className = "org.uddi.digitalindiatx.service.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://uddi.org/digitalindiatx/service", className = "org.uddi.digitalindiatx.service.PayResponse")
    public PayRecept pay(
        @WebParam(name = "to-account", targetNamespace = "http://uddi.org/digitalindiatx/types")
        UddiPayment toAccount,
        @WebParam(name = "from-account", targetNamespace = "http://uddi.org/digitalindiatx/types")
        UddiPayment fromAccount,
        @WebParam(name = "balance", targetNamespace = "http://uddi.org/digitalindiatx/types")
        double balance);

}
